/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var MessageID_pb = require('./MessageID_pb.js');
goog.exportSymbol('proto.GamePKG.ChatMessage', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GamePKG.ChatMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GamePKG.ChatMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GamePKG.ChatMessage.displayName = 'proto.GamePKG.ChatMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GamePKG.ChatMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.GamePKG.ChatMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GamePKG.ChatMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.ChatMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    pkgid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    userid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    roleid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    rolename: jspb.Message.getFieldWithDefault(msg, 4, ""),
    channelid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    content: jspb.Message.getFieldWithDefault(msg, 6, ""),
    verifycode: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GamePKG.ChatMessage}
 */
proto.GamePKG.ChatMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GamePKG.ChatMessage;
  return proto.GamePKG.ChatMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GamePKG.ChatMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GamePKG.ChatMessage}
 */
proto.GamePKG.ChatMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.PKGTypeID} */ (reader.readEnum());
      msg.setPkgid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRoleid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRolename(value);
      break;
    case 5:
      var value = /** @type {!proto.CHATChannel} */ (reader.readEnum());
      msg.setChannelid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setVerifycode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GamePKG.ChatMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GamePKG.ChatMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GamePKG.ChatMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.ChatMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPkgid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getRoleid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getRolename();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getChannelid();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getVerifycode();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional PKGTypeID PkgID = 1;
 * @return {!proto.PKGTypeID}
 */
proto.GamePKG.ChatMessage.prototype.getPkgid = function() {
  return /** @type {!proto.PKGTypeID} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.PKGTypeID} value */
proto.GamePKG.ChatMessage.prototype.setPkgid = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint64 UserID = 2;
 * @return {number}
 */
proto.GamePKG.ChatMessage.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.GamePKG.ChatMessage.prototype.setUserid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 RoleID = 3;
 * @return {number}
 */
proto.GamePKG.ChatMessage.prototype.getRoleid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.GamePKG.ChatMessage.prototype.setRoleid = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string RoleName = 4;
 * @return {string}
 */
proto.GamePKG.ChatMessage.prototype.getRolename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.GamePKG.ChatMessage.prototype.setRolename = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional CHATChannel ChannelID = 5;
 * @return {!proto.CHATChannel}
 */
proto.GamePKG.ChatMessage.prototype.getChannelid = function() {
  return /** @type {!proto.CHATChannel} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.CHATChannel} value */
proto.GamePKG.ChatMessage.prototype.setChannelid = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string Content = 6;
 * @return {string}
 */
proto.GamePKG.ChatMessage.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.GamePKG.ChatMessage.prototype.setContent = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string VerifyCode = 7;
 * @return {string}
 */
proto.GamePKG.ChatMessage.prototype.getVerifycode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.GamePKG.ChatMessage.prototype.setVerifycode = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


goog.object.extend(exports, proto.GamePKG);
