/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var MessageID_pb = require('./MessageID_pb.js');
goog.exportSymbol('proto.GamePKG.History', null, global);
goog.exportSymbol('proto.GamePKG.Quest', null, global);
goog.exportSymbol('proto.GamePKG.QuestContent', null, global);
goog.exportSymbol('proto.GamePKG.QuestList', null, global);
goog.exportSymbol('proto.GamePKG.QuestOperate', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GamePKG.QuestContent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GamePKG.QuestContent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GamePKG.QuestContent.displayName = 'proto.GamePKG.QuestContent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GamePKG.QuestContent.prototype.toObject = function(opt_includeInstance) {
  return proto.GamePKG.QuestContent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GamePKG.QuestContent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.QuestContent.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    param1: jspb.Message.getFieldWithDefault(msg, 2, 0),
    param2: jspb.Message.getFieldWithDefault(msg, 3, 0),
    param3: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GamePKG.QuestContent}
 */
proto.GamePKG.QuestContent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GamePKG.QuestContent;
  return proto.GamePKG.QuestContent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GamePKG.QuestContent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GamePKG.QuestContent}
 */
proto.GamePKG.QuestContent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setParam1(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setParam2(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setParam3(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GamePKG.QuestContent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GamePKG.QuestContent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GamePKG.QuestContent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.QuestContent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getParam1();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getParam2();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getParam3();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional int32 Type = 1;
 * @return {number}
 */
proto.GamePKG.QuestContent.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.GamePKG.QuestContent.prototype.setType = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 Param1 = 2;
 * @return {number}
 */
proto.GamePKG.QuestContent.prototype.getParam1 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.GamePKG.QuestContent.prototype.setParam1 = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 Param2 = 3;
 * @return {number}
 */
proto.GamePKG.QuestContent.prototype.getParam2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.GamePKG.QuestContent.prototype.setParam2 = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 Param3 = 4;
 * @return {number}
 */
proto.GamePKG.QuestContent.prototype.getParam3 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.GamePKG.QuestContent.prototype.setParam3 = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GamePKG.QuestOperate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GamePKG.QuestOperate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GamePKG.QuestOperate.displayName = 'proto.GamePKG.QuestOperate';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GamePKG.QuestOperate.prototype.toObject = function(opt_includeInstance) {
  return proto.GamePKG.QuestOperate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GamePKG.QuestOperate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.QuestOperate.toObject = function(includeInstance, msg) {
  var f, obj = {
    pkgid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    userid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    roleid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    questid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    operate: jspb.Message.getFieldWithDefault(msg, 5, 0),
    verifycode: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GamePKG.QuestOperate}
 */
proto.GamePKG.QuestOperate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GamePKG.QuestOperate;
  return proto.GamePKG.QuestOperate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GamePKG.QuestOperate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GamePKG.QuestOperate}
 */
proto.GamePKG.QuestOperate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.PKGTypeID} */ (reader.readEnum());
      msg.setPkgid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRoleid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuestid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOperate(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setVerifycode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GamePKG.QuestOperate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GamePKG.QuestOperate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GamePKG.QuestOperate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.QuestOperate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPkgid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getRoleid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getQuestid();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getOperate();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getVerifycode();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional PKGTypeID PkgID = 1;
 * @return {!proto.PKGTypeID}
 */
proto.GamePKG.QuestOperate.prototype.getPkgid = function() {
  return /** @type {!proto.PKGTypeID} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.PKGTypeID} value */
proto.GamePKG.QuestOperate.prototype.setPkgid = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint64 UserID = 2;
 * @return {number}
 */
proto.GamePKG.QuestOperate.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.GamePKG.QuestOperate.prototype.setUserid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 RoleID = 3;
 * @return {number}
 */
proto.GamePKG.QuestOperate.prototype.getRoleid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.GamePKG.QuestOperate.prototype.setRoleid = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 QuestID = 4;
 * @return {number}
 */
proto.GamePKG.QuestOperate.prototype.getQuestid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.GamePKG.QuestOperate.prototype.setQuestid = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 Operate = 5;
 * @return {number}
 */
proto.GamePKG.QuestOperate.prototype.getOperate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.GamePKG.QuestOperate.prototype.setOperate = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string VerifyCode = 6;
 * @return {string}
 */
proto.GamePKG.QuestOperate.prototype.getVerifycode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.GamePKG.QuestOperate.prototype.setVerifycode = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GamePKG.Quest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GamePKG.Quest.repeatedFields_, null);
};
goog.inherits(proto.GamePKG.Quest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GamePKG.Quest.displayName = 'proto.GamePKG.Quest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GamePKG.Quest.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GamePKG.Quest.prototype.toObject = function(opt_includeInstance) {
  return proto.GamePKG.Quest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GamePKG.Quest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.Quest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pkgid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    userid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    roleid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    questid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    accepttime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    state: jspb.Message.getFieldWithDefault(msg, 6, 0),
    contentList: jspb.Message.toObjectList(msg.getContentList(),
    proto.GamePKG.QuestContent.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GamePKG.Quest}
 */
proto.GamePKG.Quest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GamePKG.Quest;
  return proto.GamePKG.Quest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GamePKG.Quest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GamePKG.Quest}
 */
proto.GamePKG.Quest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.PKGTypeID} */ (reader.readEnum());
      msg.setPkgid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRoleid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuestid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAccepttime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setState(value);
      break;
    case 7:
      var value = new proto.GamePKG.QuestContent;
      reader.readMessage(value,proto.GamePKG.QuestContent.deserializeBinaryFromReader);
      msg.addContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GamePKG.Quest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GamePKG.Quest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GamePKG.Quest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.Quest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPkgid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getRoleid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getQuestid();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getAccepttime();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getState();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getContentList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.GamePKG.QuestContent.serializeBinaryToWriter
    );
  }
};


/**
 * optional PKGTypeID PkgID = 1;
 * @return {!proto.PKGTypeID}
 */
proto.GamePKG.Quest.prototype.getPkgid = function() {
  return /** @type {!proto.PKGTypeID} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.PKGTypeID} value */
proto.GamePKG.Quest.prototype.setPkgid = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint64 UserID = 2;
 * @return {number}
 */
proto.GamePKG.Quest.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.GamePKG.Quest.prototype.setUserid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 RoleID = 3;
 * @return {number}
 */
proto.GamePKG.Quest.prototype.getRoleid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.GamePKG.Quest.prototype.setRoleid = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 QuestID = 4;
 * @return {number}
 */
proto.GamePKG.Quest.prototype.getQuestid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.GamePKG.Quest.prototype.setQuestid = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 AcceptTime = 5;
 * @return {number}
 */
proto.GamePKG.Quest.prototype.getAccepttime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.GamePKG.Quest.prototype.setAccepttime = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 State = 6;
 * @return {number}
 */
proto.GamePKG.Quest.prototype.getState = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.GamePKG.Quest.prototype.setState = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated QuestContent Content = 7;
 * @return {!Array<!proto.GamePKG.QuestContent>}
 */
proto.GamePKG.Quest.prototype.getContentList = function() {
  return /** @type{!Array<!proto.GamePKG.QuestContent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.GamePKG.QuestContent, 7));
};


/** @param {!Array<!proto.GamePKG.QuestContent>} value */
proto.GamePKG.Quest.prototype.setContentList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.GamePKG.QuestContent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.GamePKG.QuestContent}
 */
proto.GamePKG.Quest.prototype.addContent = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.GamePKG.QuestContent, opt_index);
};


proto.GamePKG.Quest.prototype.clearContentList = function() {
  this.setContentList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GamePKG.QuestList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GamePKG.QuestList.repeatedFields_, null);
};
goog.inherits(proto.GamePKG.QuestList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GamePKG.QuestList.displayName = 'proto.GamePKG.QuestList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GamePKG.QuestList.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GamePKG.QuestList.prototype.toObject = function(opt_includeInstance) {
  return proto.GamePKG.QuestList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GamePKG.QuestList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.QuestList.toObject = function(includeInstance, msg) {
  var f, obj = {
    pkgid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    userid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    roleid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    questarrayList: jspb.Message.toObjectList(msg.getQuestarrayList(),
    proto.GamePKG.Quest.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GamePKG.QuestList}
 */
proto.GamePKG.QuestList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GamePKG.QuestList;
  return proto.GamePKG.QuestList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GamePKG.QuestList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GamePKG.QuestList}
 */
proto.GamePKG.QuestList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.PKGTypeID} */ (reader.readEnum());
      msg.setPkgid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRoleid(value);
      break;
    case 4:
      var value = new proto.GamePKG.Quest;
      reader.readMessage(value,proto.GamePKG.Quest.deserializeBinaryFromReader);
      msg.addQuestarray(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GamePKG.QuestList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GamePKG.QuestList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GamePKG.QuestList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.QuestList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPkgid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getRoleid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getQuestarrayList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.GamePKG.Quest.serializeBinaryToWriter
    );
  }
};


/**
 * optional PKGTypeID PkgID = 1;
 * @return {!proto.PKGTypeID}
 */
proto.GamePKG.QuestList.prototype.getPkgid = function() {
  return /** @type {!proto.PKGTypeID} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.PKGTypeID} value */
proto.GamePKG.QuestList.prototype.setPkgid = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint64 UserID = 2;
 * @return {number}
 */
proto.GamePKG.QuestList.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.GamePKG.QuestList.prototype.setUserid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 RoleID = 3;
 * @return {number}
 */
proto.GamePKG.QuestList.prototype.getRoleid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.GamePKG.QuestList.prototype.setRoleid = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated Quest QuestArray = 4;
 * @return {!Array<!proto.GamePKG.Quest>}
 */
proto.GamePKG.QuestList.prototype.getQuestarrayList = function() {
  return /** @type{!Array<!proto.GamePKG.Quest>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.GamePKG.Quest, 4));
};


/** @param {!Array<!proto.GamePKG.Quest>} value */
proto.GamePKG.QuestList.prototype.setQuestarrayList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.GamePKG.Quest=} opt_value
 * @param {number=} opt_index
 * @return {!proto.GamePKG.Quest}
 */
proto.GamePKG.QuestList.prototype.addQuestarray = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.GamePKG.Quest, opt_index);
};


proto.GamePKG.QuestList.prototype.clearQuestarrayList = function() {
  this.setQuestarrayList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GamePKG.History = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GamePKG.History, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GamePKG.History.displayName = 'proto.GamePKG.History';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GamePKG.History.prototype.toObject = function(opt_includeInstance) {
  return proto.GamePKG.History.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GamePKG.History} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.History.toObject = function(includeInstance, msg) {
  var f, obj = {
    pkgid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    userid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    roleid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    id: jspb.Message.getFieldWithDefault(msg, 4, 0),
    completetime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    daytimes: jspb.Message.getFieldWithDefault(msg, 6, 0),
    weektimes: jspb.Message.getFieldWithDefault(msg, 7, 0),
    monthtimes: jspb.Message.getFieldWithDefault(msg, 8, 0),
    yeartimes: jspb.Message.getFieldWithDefault(msg, 9, 0),
    counttimes: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GamePKG.History}
 */
proto.GamePKG.History.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GamePKG.History;
  return proto.GamePKG.History.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GamePKG.History} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GamePKG.History}
 */
proto.GamePKG.History.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.PKGTypeID} */ (reader.readEnum());
      msg.setPkgid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRoleid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCompletetime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDaytimes(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWeektimes(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMonthtimes(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setYeartimes(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCounttimes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GamePKG.History.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GamePKG.History.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GamePKG.History} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GamePKG.History.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPkgid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getRoleid();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getCompletetime();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDaytimes();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getWeektimes();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getMonthtimes();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getYeartimes();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getCounttimes();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
};


/**
 * optional PKGTypeID PkgID = 1;
 * @return {!proto.PKGTypeID}
 */
proto.GamePKG.History.prototype.getPkgid = function() {
  return /** @type {!proto.PKGTypeID} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.PKGTypeID} value */
proto.GamePKG.History.prototype.setPkgid = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint64 UserID = 2;
 * @return {number}
 */
proto.GamePKG.History.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setUserid = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 RoleID = 3;
 * @return {number}
 */
proto.GamePKG.History.prototype.getRoleid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setRoleid = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 ID = 4;
 * @return {number}
 */
proto.GamePKG.History.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 CompleteTime = 5;
 * @return {number}
 */
proto.GamePKG.History.prototype.getCompletetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setCompletetime = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 DayTimes = 6;
 * @return {number}
 */
proto.GamePKG.History.prototype.getDaytimes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setDaytimes = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 WeekTimes = 7;
 * @return {number}
 */
proto.GamePKG.History.prototype.getWeektimes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setWeektimes = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 MonthTimes = 8;
 * @return {number}
 */
proto.GamePKG.History.prototype.getMonthtimes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setMonthtimes = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 YearTimes = 9;
 * @return {number}
 */
proto.GamePKG.History.prototype.getYeartimes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setYeartimes = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 CountTimes = 10;
 * @return {number}
 */
proto.GamePKG.History.prototype.getCounttimes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.GamePKG.History.prototype.setCounttimes = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


goog.object.extend(exports, proto.GamePKG);
